defaults: &defaults
  additional_info: true
  contact_phone: true
  description: true
  electricity: true
  light: true
  fire: true
  noise: true
  nature: true
  moop: true
  plan: true
  cocreation: true
  neighbors: true
  recycling: true
  budgetplan: true
  seeking_members: true
  granting: true
  user_authentication_codes: true
  user_authentication_vs_tixwise: true
  add_to_list: true
  granting_active: true
  footer_text: true
  footer_logo: false
  creation_sidebar_welcome: true
  safetybag: true
  disable_open_new_dream: <%= ENV['DISABLE_OPEN_NEW_DREAM'] or false %>
  disable_edit_safetybag: <%= ENV['DISABLE_EDIT_SAFETYBAG'] or false %>
  disable_edit_budget: <%= ENV['DISABLE_EDIT_BUDGET'] or false %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
